<a href="https://colab.research.google.com/github/pitontoey/PythonDataViz2026/blob/main/Pandas_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import os
path ='/content/drive/MyDrive/DataViz2026'

In [8]:
covid_file_path = os.path.join(path,'confirmed-cases.csv')
print(covid_file_path)

/content/drive/MyDrive/DataViz2026/confirmed-cases.csv

In [9]:
a = path + '/confirmed-cases.csv'
print(a)

/content/drive/MyDrive/DataViz2026/confirmed-cases.csv

## load data to memory

In [10]:
data_covid = pd.read_csv(covid_file_path)
data_covid

,No.,announce_date,Notified date,sex,age,nationality,province_of_isolation,province_of_onset,district_of_onset,risk
0,1,12/1/20,NaN,หญิง,61.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
1,2,17/1/20,NaN,หญิง,74.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
2,3,22/1/20,NaN,หญิง,73.0,Thailand,นครปฐม,นครปฐม,เมือง,คนต่างชาติเดินทางมาจากต่างประเทศ
3,4,22/1/20,NaN,ชาย,68.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
4,5,24/1/20,NaN,หญิง,66.0,China,นนทบุรี,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
...,...,...,...,...,...,...,...,...,...,...
12648,12649,20/1/21,19/1/2021,ชาย,42.0,Thailand,สมุทรปราการ,กรุงเทพมหานคร,ลาดกระบัง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
12649,12650,20/1/21,19/1/2021,หญิง,44.0,Thailand,ชลบุรี,ชลบุรี,บางละมุง,State Quarantine
12650,12651,20/1/21,19/1/2021,หญิง,52.0,Thailand,ระยอง,ระยอง,แกลง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12651,12652,20/1/21,19/1/2021,หญิง,23.0,Thailand,ระยอง,ระยอง,นิคมพัฒนา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12652,12653,20/1/21,19/1/2021,หญิง,29.0,Thailand,ระยอง,ระยอง,เมือง,Cluster ระยอง

In [11]:
data_covid.head()

,No.,announce_date,Notified date,sex,age,nationality,province_of_isolation,province_of_onset,district_of_onset,risk
0,1,12/1/20,NaN,หญิง,61.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
1,2,17/1/20,NaN,หญิง,74.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
2,3,22/1/20,NaN,หญิง,73.0,Thailand,นครปฐม,นครปฐม,เมือง,คนต่างชาติเดินทางมาจากต่างประเทศ
3,4,22/1/20,NaN,ชาย,68.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
4,5,24/1/20,NaN,หญิง,66.0,China,นนทบุรี,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ

In [12]:
data_covid.shape

(12653, 10)

## ชี้ค่าในตาราง

#### basic

In [13]:
data_covid['province_of_onset']

0        กรุงเทพมหานคร
1        กรุงเทพมหานคร
2               นครปฐม
3        กรุงเทพมหานคร
4        กรุงเทพมหานคร
             ...
12648    กรุงเทพมหานคร
12649           ชลบุรี
12650            ระยอง
12651            ระยอง
12652            ระยอง
Name: province_of_onset, Length: 12653, dtype: object

In [14]:
data_covid['province_of_onset'][4]

'กรุงเทพมหานคร'

#### .iloc

In [15]:
data_covid.iloc[4,7]

'กรุงเทพมหานคร'

## Table slicing

#### ตัดมาเฉพาะ column ที่ต้องการ

In [16]:
smaller_table = data_covid[['announce_date','province_of_onset','risk']]
smaller_table

,announce_date,province_of_onset,risk
0,12/1/20,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ
1,17/1/20,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ
2,22/1/20,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ
3,22/1/20,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ
4,24/1/20,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ
...,...,...,...
12648,20/1/21,กรุงเทพมหานคร,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
12649,20/1/21,ชลบุรี,State Quarantine
12650,20/1/21,ระยอง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12651,20/1/21,ระยอง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12652,20/1/21,ระยอง,Cluster ระยอง

#### ตัดเฉพาะ rows ที่ต้องการ

##### แบบง่าย แต่ใช้การอะไรไม่ค่อยจะได้ (มองเป็น array แล้วตัดแบบ array)

In [17]:
data_covid.iloc[1:5,:]

,No.,announce_date,Notified date,sex,age,nationality,province_of_isolation,province_of_onset,district_of_onset,risk
1,2,17/1/20,NaN,หญิง,74.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
2,3,22/1/20,NaN,หญิง,73.0,Thailand,นครปฐม,นครปฐม,เมือง,คนต่างชาติเดินทางมาจากต่างประเทศ
3,4,22/1/20,NaN,ชาย,68.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
4,5,24/1/20,NaN,หญิง,66.0,China,นนทบุรี,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ

แบบ advanced แต่ใช้ประโยชน์ได้เยอะกว่า (ตัดแบบใช้ logic query)

In [18]:
data_covid[data_covid['province_of_onset']=='ขอนแก่น']

,No.,announce_date,Notified date,sex,age,nationality,province_of_isolation,province_of_onset,district_of_onset,risk
181,182,18/3/20,15/3/2020,ชาย,33.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,สนามมวย
463,464,22/3/20,21/3/2020,หญิง,36.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1467,1468,30/3/20,26/3/2020,ชาย,19.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,คนไทยเดินทางกลับจากต่างประเทศ
1971,1972,3/4/20,31/3/2020,หญิง,70.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
2638,2639,15/4/20,14/4/2020,หญิง,63.0,Thailand,ขอนแก่น,ขอนแก่น,น้ำพอง,สัมผัสผู้เดินทางจากต่างประเทศ
2674,2675,17/4/20,16/4/2020,ชาย,68.0,Thailand,ขอนแก่น,ขอนแก่น,น้ำพอง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
5949,5950,26/12/20,25/12/2020,หญิง,32.0,Thailand,ขอนแก่น,ขอนแก่น,แวงใหญ่,Cluster สมุทรสาคร
6083,6084,27/12/20,26/12/2020,หญิง,36.0,Thailand,ขอนแก่น,ขอนแก่น,แวงใหญ่,Cluster สมุทรสาคร
9334,9335,7/1/21,6/1/2021,ชาย,17.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,อยู่ระหว่างการสอบสวน
9335,9336,7/1/21,6/1/2021,ชาย,20.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
10611,10612,12/1/21,11/1/2021,ชาย,17.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11518,11519,16/1/21,15/1/2021,ชาย,12.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,อยู่ระหว่างการสอบสวน
11698,11699,17/1/21,16/1/2021,หญิง,17.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11699,11700,17/1/21,16/1/2021,หญิง,37.0,Thailand,ขอนแก่น,ขอนแก่น,เมือง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

การชี้ค่าในตารางด้วย data_covid[***x***] ค่า ***x*** สามารถมีค่าที่ใส่เข้าไปได้ 2 แบบ


1.   ชื่อ column
2.   ใส่ rows ที่ต้องการ (ใส่ list ที่มี***ขนาดเท่ากับจำนวนแถว*** แล้วบอกว่าเอา แถวไหนบ้างโดยใช้ logical expression (```True```/```False```))

In [19]:
eight_rows_covid = data_covid.iloc[:8,:] # ตารางตัวอย่าง
eight_rows_covid

,No.,announce_date,Notified date,sex,age,nationality,province_of_isolation,province_of_onset,district_of_onset,risk
0,1,12/1/20,NaN,หญิง,61.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
1,2,17/1/20,NaN,หญิง,74.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
2,3,22/1/20,NaN,หญิง,73.0,Thailand,นครปฐม,นครปฐม,เมือง,คนต่างชาติเดินทางมาจากต่างประเทศ
3,4,22/1/20,NaN,ชาย,68.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
4,5,24/1/20,NaN,หญิง,66.0,China,นนทบุรี,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
5,6,25/1/20,NaN,หญิง,33.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
6,7,26/1/20,NaN,หญิง,57.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
7,8,26/1/20,NaN,หญิง,73.0,China,ประจวบคีรีขันธ์,ประจวบคีรีขันธ์,หัวหิน,คนต่างชาติเดินทางมาจากต่างประเทศ

In [20]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]   #2.   ใส่ rows ที่ต้องการ

,No.,announce_date,Notified date,sex,age,nationality,province_of_isolation,province_of_onset,district_of_onset,risk
0,1,12/1/20,NaN,หญิง,61.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
2,3,22/1/20,NaN,หญิง,73.0,Thailand,นครปฐม,นครปฐม,เมือง,คนต่างชาติเดินทางมาจากต่างประเทศ
3,4,22/1/20,NaN,ชาย,68.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
5,6,25/1/20,NaN,หญิง,33.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ

In [21]:
eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร'  #สร้าง list ของ logical expression

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: province_of_onset, dtype: bool

In [22]:
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร']  #เราเอา 2 บรรทัดบนมาบวกกัน

,No.,announce_date,Notified date,sex,age,nationality,province_of_isolation,province_of_onset,district_of_onset,risk
0,1,12/1/20,NaN,หญิง,61.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
1,2,17/1/20,NaN,หญิง,74.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
3,4,22/1/20,NaN,ชาย,68.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
4,5,24/1/20,NaN,หญิง,66.0,China,นนทบุรี,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
5,6,25/1/20,NaN,หญิง,33.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ
6,7,26/1/20,NaN,หญิง,57.0,China,กรุงเทพมหานคร,กรุงเทพมหานคร,NaN,คนต่างชาติเดินทางมาจากต่างประเทศ

# *HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)*

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

In [23]:
this_data = data_covid[['sex','age','province_of_onset']]

In [24]:
this_data

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648   ชาย  42.0     กรุงเทพมหานคร
12649  หญิง  44.0            ชลบุรี
12650  หญิง  52.0             ระยอง
12651  หญิง  23.0             ระยอง
12652  หญิง  29.0             ระยอง

[12653 rows x 3 columns]

In [25]:
female = this_data[this_data['sex']=='หญิง']
female['age']

0        61.0
1        74.0
2        73.0
4        66.0
5        33.0
         ...
12646    44.0
12649    44.0
12650    52.0
12651    23.0
12652    29.0
Name: age, Length: 5917, dtype: float64

In [26]:
sum = 0
N = 0
for a in female['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง {sum/N}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง 36.10576731191379

In [27]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']

sum = 0
N = 0
for a in female_KK['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum/N}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 41.57142857142857

การจัดการ Missing Value

- ลบ record ที่เป็น missing
- แทนที่ ค่า missing ด้วยค่าที่เหมาะสม mean, default, category-unknown
- ใช้ ค่าจาก columns อื่นๆ ช่วยประมาณค่า ค่าใน column ที่หายไป (regression, deep learning, etc.)

### ลบ record (dropna)

missing = ```None``` ```NA```(not autorized) ```NaN``` (not a number)

In [28]:
this_data.shape #(12423, 3)

(12653, 3)

In [29]:
print(data_covid.shape)
print(data_covid.dropna().shape)

(12653, 10)
(7315, 10)

In [30]:
this_data.dropna().shape

(9144, 3)

In [31]:
this_data.dropna()

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648   ชาย  42.0     กรุงเทพมหานคร
12649  หญิง  44.0            ชลบุรี
12650  หญิง  52.0             ระยอง
12651  หญิง  23.0             ระยอง
12652  หญิง  29.0             ระยอง

[9144 rows x 3 columns]

In [32]:
this_data.dropna()
print(this_data.shape)

(12653, 3)

In [33]:
this_data.dropna(inplace=True)

/tmp/ipykernel_965/3935554116.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

In [34]:
this_data.dropna(inplace=True)
print(this_data.shape)

(9144, 3)

/tmp/ipykernel_965/2129530393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

In [35]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data.shape

(12653, 3)

In [36]:
this_data.dropna().shape

(9144, 3)

In [37]:
this_data.dropna(subset=['age']).shape

(9787, 3)

### แทน missing ด้วยค่าที่เหมาะสม (```fillna```)

In [38]:
this_data = data_covid[['sex','age','province_of_onset']]

In [39]:
this_data.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [40]:
print(f'จำนวน record ก่อน drop missing ใน province {this_data.shape[0]}')
print(f'จำนวน record หลัง drop missing ใน province {this_data.dropna(subset=["province_of_onset"]).shape[0]}')

จำนวน record ก่อน drop missing ใน province 12653
จำนวน record หลัง drop missing ใน province 11317

In [41]:
this_data_updated = this_data.fillna(value={'sex':'ไม่รู้', 'age':-1, 'province_of_onset':'ไม่รู้'})
this_data_updated.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [42]:
this_data_updated[this_data_updated['sex']=='ไม่รู้']

         sex  age province_of_onset
4397  ไม่รู้ -1.0         สมุทรสาคร
4398  ไม่รู้ -1.0         สมุทรสาคร
4399  ไม่รู้ -1.0         สมุทรสาคร
4400  ไม่รู้ -1.0         สมุทรสาคร
4401  ไม่รู้ -1.0         สมุทรสาคร
...      ...  ...               ...
7692  ไม่รู้ -1.0            ไม่รู้
7693  ไม่รู้ -1.0            ไม่รู้
7694  ไม่รู้ -1.0            ไม่รู้
8395  ไม่รู้ -1.0            ไม่รู้
8544  ไม่รู้ -1.0         สมุทรสาคร

[1609 rows x 3 columns]

In [43]:
this_data_updated['province_of_onset']=='ไม่รู้'

0        False
1        False
2        False
3        False
4        False
         ...
12648    False
12649    False
12650    False
12651    False
12652    False
Name: province_of_onset, Length: 12653, dtype: bool

In [44]:
data_covid[this_data_updated['province_of_onset']=='ไม่รู้']

,No.,announce_date,Notified date,sex,age,nationality,province_of_isolation,province_of_onset,district_of_onset,risk
415,416,22/3/20,22/3/2020,ชาย,29.0,Thailand,กรุงเทพมหานคร,NaN,NaN,สนามมวย
530,531,22/3/20,20/3/2020,ชาย,37.0,Thailand,กรุงเทพมหานคร,NaN,NaN,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
556,557,22/3/20,21/3/2020,หญิง,6.0,Thailand,กรุงเทพมหานคร,NaN,NaN,สนามมวย
577,578,22/3/20,20/3/2020,ชาย,NaN,Thailand,กรุงเทพมหานคร,NaN,NaN,สนามมวย
589,590,22/3/20,21/3/2020,ชาย,NaN,Thailand,กรุงเทพมหานคร,NaN,NaN,อยู่ระหว่างการสอบสวน
...,...,...,...,...,...,...,...,...,...,...
12406,12407,18/1/21,17/1/2021,หญิง,36.0,Burma,สมุทรสาคร,NaN,NaN,Cluster สมุทรสาคร
12407,12408,18/1/21,17/1/2021,หญิง,24.0,Burma,สมุทรสาคร,NaN,NaN,Cluster สมุทรสาคร
12408,12409,18/1/21,17/1/2021,ชาย,43.0,Burma,สมุทรสาคร,NaN,NaN,Cluster สมุทรสาคร
12409,12410,18/1/21,17/1/2021,ชาย,37.0,Burma,สมุทรสาคร,NaN,NaN,Cluster สมุทรสาคร
12410,12411,18/1/21,17/1/2021,ชาย,33.0,Burma,สมุทรสาคร,NaN,NaN,Cluster สมุทรสาคร

In [45]:
this_data_updated_2 = this_data.fillna(value={'province_of_onset':'ไม่รู้'})

In [46]:
this_data_updated_2[this_data_updated['sex']=='ไม่รู้']

      sex  age province_of_onset
4397  NaN  NaN         สมุทรสาคร
4398  NaN  NaN         สมุทรสาคร
4399  NaN  NaN         สมุทรสาคร
4400  NaN  NaN         สมุทรสาคร
4401  NaN  NaN         สมุทรสาคร
...   ...  ...               ...
7692  NaN  NaN            ไม่รู้
7693  NaN  NaN            ไม่รู้
7694  NaN  NaN            ไม่รู้
8395  NaN  NaN            ไม่รู้
8544  NaN  NaN         สมุทรสาคร

[1609 rows x 3 columns]

### การวนลูป record ในตาราง  (```.iterrows```)

In [47]:
this_data = data_covid[['sex','age','province_of_onset']]

In [48]:
for each_row in this_data.iterrows():
    # print(each_row)
    # print(each_row[1])
    if (each_row[1]['age'] == 20) and (each_row[1]['province_of_onset'] == 'ขอนแก่น'):
        print(each_row)

(9335, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 9335, dtype: object)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```)

In [49]:
for each_row in range(this_data.shape[0]):
    if (this_data.iloc[each_row,1] == 20) and (this_data.iloc[each_row,2] == 'ขอนแก่น'):  #each_row คือ ตัวเลข
        print(each_row)
        print(this_data.iloc[each_row,:])

9335
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 9335, dtype: object

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [50]:
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

Empty DataFrame
Columns: [No., announce_date, Notified date, sex, age, nationality, province_of_isolation, province_of_onset, district_of_onset, risk]
Index: []

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [52]:
data_covid.describe()

                No.          age
count  12653.000000  9787.000000
mean    6327.000000    37.514969
std     3652.750813    14.738641
min        1.000000     1.000000
25%     3164.000000    27.000000
50%     6327.000000    35.000000
75%     9490.000000    47.000000
max    12653.000000    97.000000

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [53]:
data_covid[data_covid['sex']=='ชาย']['age'].mean()

np.float64(38.99581151832461)

### ```.isnull()```

In [54]:
data_covid.isnull()

,No.,announce_date,Notified date,sex,age,nationality,province_of_isolation,province_of_onset,district_of_onset,risk
0,False,False,True,False,False,False,False,False,True,False
1,False,False,True,False,False,False,False,False,True,False
2,False,False,True,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,True,False
4,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...
12648,False,False,False,False,False,False,False,False,False,False
12649,False,False,False,False,False,False,False,False,False,False
12650,False,False,False,False,False,False,False,False,False,False
12651,False,False,False,False,False,False,False,False,False,False
12652,False,False,False,False,False,False,False,False,False,False

# next
*   .describe
*   .mean
*   HW วนลูป missing .isnull
*   ต่อตารางแกน X แกน y
*   .groupby
*   save table